# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class MyServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.handle_request = channel.unary_unary(
        '/MyService/handle_request',
        request_serializer=service__pb2.Request.SerializeToString,
        response_deserializer=service__pb2.Response.FromString,
        )


class MyServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def handle_request(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MyServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'handle_request': grpc.unary_unary_rpc_method_handler(
          servicer.handle_request,
          request_deserializer=service__pb2.Request.FromString,
          response_serializer=service__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MyService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
